name: multi_stack_navigator
description: Flutter navigation package with deep links and nested navigation support. Built on Navigator 2.0.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.2
  flutter:
    sdk: flutter  
  uri: ^1.0.0

dev_dependencies:
  matcher: ^0.12.16
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

